org: enzogomez
service: programa-service

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: dev
  iam:
    role: arn:aws:iam::353553552499:role/LabRole

functions:
  createProgram:
    handler: create_program.lambda_handler  # Archivo 'create_program.py' y funci贸n 'lambda_handler'
    events:
      - http:
          path: programa/create
          method: post
          cors: true
          integration: lambda

  searchProgram:
    handler: search_program.lambda_handler  
    events:
      - http:
          path: programa/search
          method: post
          cors: true
          integration: lambda

  deleteProgram:
    handler: delete_program.lambda_handler  # Archivo 'delete_program.py' y funci贸n 'lambda_handler'
    events:
      - http:
          path: programa/delete
          method: post
          cors: true
          integration: lambda

  createEstudiante:
    handler: create_estudiante.lambda_handler  
    events:
      - http:
          path: estudiante/create
          method: post
          cors: true
          integration: lambda

  searchEstudiante:
    handler: search_estudiante.lambda_handler  # Archivo 'search_estudiante.py' y funci贸n 'lambda_handler'
    events:
      - http:
          path: estudiante/search
          method: post
          cors: true
          integration: lambda
          
  deleteEstudiante:
    handler: delete_estudiante.lambda_handler  # Archivo 'delete_estudiante.py' y funci贸n 'lambda_handler'
    events:
      - http:
          path: estudiante/delete
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    EstudiantesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: estudiantes
        AttributeDefinitions:
          - AttributeName: "id_estudiante"
            AttributeType: "S"
          - AttributeName: "dni"
            AttributeType: "S"
          
        KeySchema:
          - AttributeName: "id_estudiante"
            KeyType: "HASH"
          - AttributeName: "dni"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    ProgramaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: programa
        AttributeDefinitions:
          - AttributeName: "id_programa"
            AttributeType: "S"
          - AttributeName: "fecha_inicio"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id_programa"
            KeyType: "HASH"
          - AttributeName: "fecha_inicio"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5