org: enzogomez
service: programa-service
#enzo
provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: dev
  iam:
    role: arn:aws:iam::353553552499:role/LabRole

functions:
  createProgram:
    handler: handler.create_program
    events:
      - http:
          path: programa/create
          method: post
          cors: true
          integration: lambda

  searchProgram:
    handler: handler.search_program
    events:
      - http:
          path: programa/search
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    EstudiantesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: estudiantes
        AttributeDefinitions:
          - AttributeName: "id_estudiante"
            AttributeType: "S"
          - AttributeName: "dni"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id_estudiante"
            KeyType: "HASH"
          - AttributeName: "dni"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    ProgramaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: programa
        AttributeDefinitions:
          - AttributeName: "pais_destino"
            AttributeType: "S"
          - AttributeName: "fecha_inicio"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "pais_destino"
            KeyType: "HASH"
          - AttributeName: "fecha_inicio"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
